import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer/Footer";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Finanční Svět",
    description: "Generated by create next app",
    charset: "utf-8",
    icon: "/icon.png",
};

export default function RootLayout({children}) {
    return (
        <html lang="cs">
            <body className={inter.className}>
                <Navbar/>
                    {children}
                <Footer/>
            </body>
        </html>
    );
}
