import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import {ThemeProvider} from "next-themes";
import {SpeedInsights} from "@vercel/speed-insights/next"
import {Analytics} from "@vercel/analytics/react"
import styles from "./page.module.css"
import dynamic from "next/dynamic";
import { Noto_Sans } from 'next/font/google'

const font = Noto_Sans({
    weight: '400',
    subsets: ['latin'],
})

const ColorButton = dynamic(() => import("@/components/ColorButton/ColorButton"), {
    ssr: false
})

export const metadata = {
    title: "Finanční Svět",
    description: "Generated by create next app",
    charset: "utf-8",
    icon: "/icon.png",
};

export default function RootLayout({children}) {
    return (
        <html lang="cs">
        <body className={font.className}>
        <ThemeProvider>
            <SpeedInsights/>
            <Analytics/>
            <Navbar/>
            <ColorButton/>
            <main className={styles.main}>
                {children}
            </main>
            <Footer/>
        </ThemeProvider>
        </body>
        </html>
    );
}
