import {Inter} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import {ThemeProvider} from "next-themes";
import {SpeedInsights} from "@vercel/speed-insights/next"
import {Analytics} from "@vercel/analytics/react"
import styles from "./page.module.css"
import dynamic from "next/dynamic";

const ColorButton = dynamic(() => import("@/components/ColorButton/ColorButton"), {
    ssr: false
})

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Finanční Svět",
    description: "Generated by create next app",
    charset: "utf-8",
    icon: "/icon.png",
};

export default function RootLayout({children}) {
    return (
        <html lang="cs">
        <body className={inter.className}>
        <ThemeProvider>
            <SpeedInsights/>
            <Analytics/>
            <Navbar/>
            <ColorButton/>
            <main className={styles.main}>
                {children}
            </main>
            <Footer/>
        </ThemeProvider>
        </body>
        </html>
    );
}
